.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-DOCS" "1" "May 2016" "" "Git Extras"
.
.SH "NAME"
\fBgit\-docs\fR \- Create/Merge docs branch
.
.SH "SYNOPSIS"
\fBgit\-docs\fR [\-a|\-\-alias branch_prefix] [finish] <name>
.
.SH "DESCRIPTION"
Create/Merge the given docs branch
.
.SH "OPTIONS"
<\-a|\-\-alias branch_prefix>
.
.P
use \fBbranch_prefix\fR instead of \fBdocs\fR
.
.P
<finish>
.
.P
Merge and delete the docs branch\.
.
.P
<name>
.
.P
The name of the docs branch\.
.
.SH "EXAMPLES"
.
.nf

$ git docs dependencies
\.\.\.
$ (docs/dependencies) git commit \-m "Some changes"
\.\.\.
$ (docs/dependencies) git checkout master
$ git docs finish dependencies

$ git alias docss "docs \-a docss"
$ git docss dependencies
$ (docss/dependencies) \.\.\.
$ (docss/dependencies) git checkout master
$ git docss finish dependencies
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
