.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-FIX" "1" "May 2016" "" "Git Extras"
.
.SH "NAME"
\fBgit\-fix\fR \- Create/Merge fix branch
.
.SH "SYNOPSIS"
\fBgit\-fix\fR [\-a|\-\-alias branch_prefix] [finish] <name>
.
.SH "DESCRIPTION"
Create/Merge the given fix branch
.
.SH "OPTIONS"
<\-a|\-\-alias branch_prefix>
.
.P
use \fBbranch_prefix\fR instead of \fBfix\fR
.
.P
<finish>
.
.P
Merge and delete the fix branch\.
.
.P
<name>
.
.P
The name of the fix branch\.
.
.SH "EXAMPLES"
.
.nf

$ git fix dependencies
\.\.\.
$ (fix/dependencies) git commit \-m "Some changes"
\.\.\.
$ (fix/dependencies) git checkout master
$ git fix finish dependencies

$ git alias fixs "fix \-a fixs"
$ git fixs dependencies
$ (fixs/dependencies) \.\.\.
$ (fixs/dependencies) git checkout master
$ git fixs finish dependencies
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
